# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UAZ
                                 A QGIS plugin
 This plugin will be used to prepare UAZ file for feeding into OWI 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-10
        copyright            : (C) 2019 by Junaid Abdul Jabbar
        email                : junaid.abdul.jabbar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UAZ class from file UAZ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .UAZ import UAZ
    return UAZ(iface)
